### ISSUE TITLE
Insecure MySQL setup

### ISSUE THREAD

**Issue by 1Conan** [FlamesRunner/FlamesCP#1]
```
mysql -uroot -e "SET PASSWORD FOR 'root'@'localhost' = PASSWORD('stapHunu3A'); flush privileges;"
```

Anyone who knows this panel and found servers running it could gain instant access to root (password is embed at the installation)

I'd recommend generating a random password. There are a few ways to do it from bash.
http://www.howtogeek.com/howto/30184/10-ways-to-generate-a-random-password-from-the-command-line/
Or through that random.org api

**Comment by FlamesRunner** [comment]
Hey,

Yeah, I already know about this bug.
KwiceroLTD had reported to me.
Currently, I'm working on a fix, and it should be fixed soon.

Thanks!

**Comment by 1Conan** [comment]
One more thing I can recommend. Use a normal user instead of root.

**Comment by FlamesRunner** [comment]
Got that :)
I'm redeveloping the panel when I have time, right now, I'm working on
FlamesPanel, and it has a Minecraft server function.

PM me on FreeVPS for an invite/upgrade key.
