### ISSUE TITLE
Encrypt passwords on Database.

### ISSUE THREAD

**Issue by 1Conan** [FlamesRunner/FlamesCP#10]
Passwords are stored as plain text.

Use hash() with a salt to encrypt it.

**Comment by FlamesRunner** [comment]
Understood.
Sorry for the late reply.

**Comment by 1Conan** [comment]
I was gonna do this last month but I don't really have much time. 
I also don't have a CentOS 6 server available for development.

Maybe I'll try doing this on xmas break.

**Comment by FlamesRunner** [comment]
Heh, I just added MD5 hashing.
No, it's not out of this world, but it's better than plain text.

Feel free to change it to hash with a salt, etc.

**Comment by 1Conan** [comment]
Just focus on developing the functions on the panel. I'll finish this next week.

**Comment by FlamesRunner** [comment]
Thanks.
Will do.

**Comment by 1Conan** [comment]
I'll finish it tomorrow I guess.
Please don't close it since I still haven't done it.

**Comment by FlamesRunner** [comment]
Huh?

The MD5 encryption works, I already tested it.

But if you want, I can revert it.

**Comment by 1Conan** [comment]
My eyes are fooling me then (I checked the files again. I checked it while I was sleepy .-.) xD

MD5 is not recommended though. No one wants security breaches.

**Comment by FlamesRunner** [comment]
I know, so feel free to use SHA + salts.

**Comment by 1Conan** [comment]
Done on pull request #15

**Comment by 1Conan** [comment]
@FlamesRunner Any updates on testing it?

**Comment by FlamesRunner** [comment]
Yep. Sorry for not replying; I've tested it and it works fine.

Thanks for your contributions.

**Comment by 1Conan** [comment]
Okay. Thanks for testing it!
