### ISSUE TITLE
Use PDO or MySQLi everywhere

### ISSUE THREAD

**Issue by 1Conan** [FlamesRunner/FlamesCP#16]
I can still see mysql_* functions in some files.

As far as I know it is removed in php7 so this panel breaks if php7 is used. (Which can be fixed by running php5 as an fpm instance and using that as the php processor. But future proofing is better isn't it?)

If you want something easier to use you can use meekrodb. meekro.com

**Comment by FlamesRunner** [comment]
Yeah, sorry again about the wait; mind telling me where these files reside?
It'll make it easier to fix if I know where they are.

**Comment by 1Conan** [comment]
Oh so it's only 1 file.
https://github.com/FlamesRunner/FlamesCP/blob/master/password.php
I'll just do a commit for it I guess.

**Comment by 1Conan** [comment]
Should be done with dad5d04

**Comment by FlamesRunner** [comment]
Good. I'll close the issue ticket.
