### ISSUE TITLE
Convert GET to POST on login.php

### ISSUE THREAD

**Issue by 1Conan** [FlamesRunner/FlamesCP#9]

**Comment by hidden-refuge** [comment]
I miss your reason(s) or intention(s) for this Conan.

It might be GET on purpose to hide given parameter values and it also looks better with GET. I think FlamesRunner had a reason to use GET.

**Comment by 1Conan** [comment]
I was talking about login.php.

If you check, the password and usernames are using GET.

**Comment by hidden-refuge** [comment]
Sorry, nevermind. I alway mix up GET with POST. GET makes it visible in the URL which is insecure. So I agree. POST should be used. Even if it only would be a hash it would be more secure to hide it from the URL.

**Comment by 1Conan** [comment]
It's probably one of the wrong practices that Kwicero told FlamesRunner.
